### ISSUE TITLE
Feature request: post button at top of page.

### ISSUE THREAD

**Issue by Armag3ddon** [spuxx1701/potber-client#57] opened 2023-03-01 12:20 UTC
When writing a new post, the send button is at the bottom of the page. To reach it, one has to close the keyboard first. A button at the top would mitigate this. I'd generally consider it a no-no to put controls below input fields that require keyboard inputs.

Platform: Android/Vivaldi

**Comment by spuxx1701** [comment] 2023-09-07 08:18
This could also be fixed by accounting for the change in viewport height caused by the virtual keyboard, which might actually be the best solution since it'd also make it easier to scroll down to read prior posts.

**Comment by spuxx1701** [comment] 2023-09-07 11:02
implemented in 94126408f8ccdf89fb80a141f89b8b062db87155

**Closed by spuxx1701** 2023-09-07 11:02 UTC
Labels: enhancement
